### ISSUE TITLE
Failing to build on Arch Linux

### ISSUE THREAD

**Issue by caniko** [knaidoo29/mistree#23]
I have numpy installed, but I still get this error:
```
 ╭─can@pyramidal in repo: mask_to_mesh on  master [!?] is  v0.1.0 via  v3.10.13 (mask-to-mesh-py3.10) took 27s
[🔴] × poetry run pip install mistree
Collecting mistree
  Downloading mistree-1.2.2.tar.gz (29 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/can/.cache/pypoetry/virtualenvs/mask-to-mesh-dT1QsCdw-py3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/can/.cache/pypoetry/virtualenvs/mask-to-mesh-dT1QsCdw-py3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/can/.cache/pypoetry/virtualenvs/mask-to-mesh-dT1QsCdw-py3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-k081b9ip/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-k081b9ip/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-k081b9ip/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-k081b9ip/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'numpy'
```

Seem it is a temporary environment, considering it is under `/tmp`.

**Comment by knaidoo29** [comment]
@caniko hi, this is odd. It looks like the issue is coming from `subprocess` rather than `mistree`. I'm not sure why that would happen.

**Comment by knaidoo29** [comment]
Not heard anything regarding this error, and I think version 2.0.0 should probably make this issue go away anyway so I will close the issue.
